name: kbozak

services:
  eshopdb:
    image: postgres:17

  distributedcache:
    image: redis:8

  seq:
    image: datalust/seq:latest

  messagebus:
    image: rabbitmq:4-management

  identity:
    image: quay.io/keycloak/keycloak:26.0

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

volumes:
  postgres_kbozak:
