services:
  eshopdb:
    container_name: kbozak-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EShopDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_kbozak:/var/lib/postgresql/data/

  distributedcache:
    container_name: kbozak-cache
    restart: always
    ports:
      - "6379:6379"

  seq:
    container_name: kbozak-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    restart: always
    ports:
      - "5341:5341"
      - "9091:80"

  messagebus:
    container_name: kbozak-mq
    hostname: kbozak-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  identity:
    container_name: kbozak-identity
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://kbozak-db/EShopDb
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HOSTNAME=http://localhost:9090/
      - KC_HTTP_PORT=9090
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - eshopdb
    command:
      - start-dev

  api:
    container_name: kbozak-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=kbozak-db;Port=5432;Database=EShopDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=kbozak-cache:6379
      - MessageBroker__Host=amqp://kbozak-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - Keycloak__AuthServerUrl=http://kbozak-identity:9090/
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__Using__1=Serilog.Sinks.Seq
      - Serilog__MinimumLevel__Default=Information
      - Serilog__MinimumLevel__Override__Microsoft=Information
      - Serilog__MinimumLevel__Override__System=Warning
      - Serilog__WriteTo__0__Name=Console
      - Serilog__WriteTo__1__Name=Seq
      - Serilog__WriteTo__1__Args__serverUrl=http://kbozak-seq:5341
      - Serilog__Enrich__0=FromLogContext
      - Serilog__Enrich__1=WithMachineName
      - Serilog__Enrich__2=WithProcessId
      - Serilog__Enrich__3=WithThreadId
      - Serilog__Properties__Application=KBozakCSharpModularMonolith
      - Serilog__Properties__Environment=Development
    depends_on:
      - eshopdb
      - distributedcache
      - seq
      - messagebus
      - identity
    ports:
      - "8888:8080"
